import { Metadata } from "next";
import { Inter } from "next/font/google";
import { useEffect } from "react";
import "./globals.css";
import { createStore, Provider, atom } from "jotai";
import type { StateData } from "@/app/counties/types";

const inter = Inter({ subsets: ["latin"] });

const stateStore = createStore();

/*
export const metadata: Metadata = {

  title: "Voter Purge Project",
  description: "Generated by create next app",
};*/

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={stateStore}>{children}</Provider>
      </body>
    </html>
  );
}
